apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mern-app
  template:
    metadata:
      labels:
        app: mern-app
    spec:
      containers:
      - name: mern-app
        image: junjanctl/mern-app:latest
        ports:
        - containerPort: 7000
        env:
        - name: MONGO_URI
          value: mongodb://mongodb-service:27017/mydb
        - name: PORT
          value: "7000"